model:
  _target_: models.bert.BERTRanker
  lr: 0.00003
  warmup_steps: 1000
  hparams:
    bert_model: bert-base-uncased
    dropout: 0.1
    freeze_bert: False

data_processor:
  _target_: models.bert.BERTDataProcessor
  bert_model: ${ranker.model.hparams.bert_model}
  char_limit: 10000
